## [데이터 필터링]

- DataFrame/ Series에서 원하는 데이터만 추출
- 불린 인덱싱
- 메서드 isin()
- 메서드 query()

In [1]:
## [1] 모듈 로딩 및 데이터 준비
import pandas as pd

DATA_FILE='../Data/학생관리부.xlsx'

In [2]:
## [2] 데이터 로딩 및 기본정보 출력
dataDF= pd.read_excel(DATA_FILE, header=2)
dataDF

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [4]:
## [3] 특정 조건에 맞는 데이터마 추출 즉, 필터링
## [3-1] 석차가 상위 10위까지만 데이터 추출

dataDF.columns[3]

' 석차'

In [5]:
## 비교 연산으로 True/ False로 구성된 Series

boolSR=dataDF[dataDF.columns[-1]] <=10

In [6]:
## 상위 10위 안에 있는 데이터만 추출

dataDF[boolSR]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
3  박길동   3  1    9

In [7]:
## 상위 10위 밖에 있는 데이터만 추출
## !: not 연산자, 현재결과를 반대로

dataDF[~boolSR]

    이름  학년  반   석차
2  이길동   1  7   12
4  최길동   2  1   43

In [30]:
## [3-2] 1학년 중에 상위 10위 이내에 들어가는 학생 데이터

dataDF= pd.read_excel(DATA_FILE, header=2)
dataDF
maskSR= (dataDF[dataDF.columns[1]]== 1) & (dataDF[dataDF.columns[-1]]<=10)


dataDF[maskSR]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1

In [ ]:
|

: