### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [3]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [4]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [5]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [6]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [7]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [8]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [9]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [10]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    324 non-null    object
 1   전입지별    324 non-null    object
 2   1970    324 non-null    int64
 3   1971    324 non-null    int64
 4   1972    324 non-null    int64
 5   1973    324 non-null    int64
 6   1974    324 non-null    int64
 7   1975    324 non-null    int64
 8   1976    324 non-null    int64
 9   1977    324 non-null    int64
 10  1978    324 non-null    int64
 11  1979    324 non-null    int64
 12  1980    324 non-null    int64
 13  1981    324 non-null    int64
 14  1982    324 non-null    int64
 15  1983    324 non-null    int64
 16  1984    324 non-null    int64
 17  1985    324 non-null    int64
 18  1986    324 non-null    int64
 19  1987    324 non-null    int64
 20  1988    324 non-null    int64
 21  1989    324 non-null    int64
 22  1990    324 non-null    int64
 23  1991    324 non-null    int64
 24  1992    324 non-null    int64
 25  1993    324 non-null    int64
 26  1994    324 non-null    int64
 27  1995    324 non-null    int64
 28  1996    324 non-null    int64
 29  1997    324 non-null    int64
 30  1998    324 non-null    int64
 31  1999    324 non-null    int64
 32  2000    324 non-null    int64
 33  2001    324 non-null    int64
 34  2002    324 non-null    int64
 35  2003    324 non-null    int64
 36  2004    324 non-null    int64
 37  2005    324 non-null    int64
 38  2006    324 non-null    int64
 39  2007    324 non-null    int64
 40  2008    324 non-null    int64
 41  2009    324 non-null    int64
 42  2010    324 non-null    int64
 43  2011    324 non-null    int64
 44  2012    324 non-null    int64
 45  2013    324 non-null    int64
 46  2014    324 non-null    int64
 47  2015    324 non-null    int64
 48  2016    324 non-null    int64
 49  2017    324 non-null    int64
dtypes: int64(48), object(2)
memory usage: 126.7+ KB

---
#### 문제 3) 연도 컬럼의 자료형을 숫자형으로 변환하세요.
[요구사항]
1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
4. 변환 후 연도 컬럼들의 자료형을 출력하세요.
5. 전체 결측치 개수를 출력하세요.
---

In [11]:
## 1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
year_cols = df.columns[2:]
year_cols

Index(['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017'],
      dtype='object')

In [12]:
## 특정 컬럼 선택 후 기본 정보 확인
yearDF = df[ year_cols ]
display( yearDF.head(3) )
yearDF.info()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,8410276,7324380,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,3307439,2589667,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,448577,389797,362202,482061,680984,805979,724664,785117,895337,809483,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1970    324 non-null    int64
 1   1971    324 non-null    int64
 2   1972    324 non-null    int64
 3   1973    324 non-null    int64
 4   1974    324 non-null    int64
 5   1975    324 non-null    int64
 6   1976    324 non-null    int64
 7   1977    324 non-null    int64
 8   1978    324 non-null    int64
 9   1979    324 non-null    int64
 10  1980    324 non-null    int64
 11  1981    324 non-null    int64
 12  1982    324 non-null    int64
 13  1983    324 non-null    int64
 14  1984    324 non-null    int64
 15  1985    324 non-null    int64
 16  1986    324 non-null    int64
 17  1987    324 non-null    int64
 18  1988    324 non-null    int64
 19  1989    324 non-null    int64
 20  1990    324 non-null    int64
 21  1991    324 non-null    int64
 22  1992    324 non-null    int64
 23  1993    324 non-null    int64
 24  1994    324 non-null    int64
 25  1995    324 non-null    int64
 26  1996    324 non-null    int64
 27  1997    324 non-null    int64
 28  1998    324 non-null    int64
 29  1999    324 non-null    int64
 30  2000    324 non-null    int64
 31  2001    324 non-null    int64
 32  2002    324 non-null    int64
 33  2003    324 non-null    int64
 34  2004    324 non-null    int64
 35  2005    324 non-null    int64
 36  2006    324 non-null    int64
 37  2007    324 non-null    int64
 38  2008    324 non-null    int64
 39  2009    324 non-null    int64
 40  2010    324 non-null    int64
 41  2011    324 non-null    int64
 42  2012    324 non-null    int64
 43  2013    324 non-null    int64
 44  2014    324 non-null    int64
 45  2015    324 non-null    int64
 46  2016    324 non-null    int64
 47  2017    324 non-null    int64
dtypes: int64(48)
memory usage: 121.6 KB

In [13]:
## -------------------------------------------------------------------------
## 2. 연도별 이동자수 데이터에 포함된 "-" 값을 특정값으로 변경하기
## -------------------------------------------------------------------------
## FutureWarning : 현재 코드는 실행되지만 앞으로 Pandas 버전 변경 시 변경 경고
## -------------------------------------------------------------------------
# C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_31568\3585299255.py:2: FutureWarning: 
# Downcasting behavior in `replace` is deprecated and will be removed in a future version. 
# To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. 
# To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
#   yearDF.replace("-", 0).astype('int')
# "-"를 0으로 바꾸는 과정 => Pandas가 내부적으로 자료형을 자동 추론
#                         여기서 자동 다운캐스팅 방식이 앞으로 바뀔 예정
# [해결]
# 가장 깔끔한 해결은 replace 후 명시적으로 infer_objects()를 호출
## -------------------------------------------------------------------------

yearDF = yearDF.replace("-", 0).infer_objects(copy=False).astype("int")

In [14]:
## [권장] 둘 다 조건에 따라 값을 바꾸는 Pandas 메서드
## => mask(조건, 변경값) : 조건이 True인 경우 값 변경 
yearDF = yearDF.mask(yearDF == "-", 0)

## => where(조건, 변경값) : 조건이 True인 값은 그대로 두고, False인 값 변경
yearDF = yearDF.where(yearDF != "-", 0).astype("int")

In [15]:
## 2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
import numpy as np
yearDF = yearDF.replace("-",np.nan)

In [16]:
## 3. 변환 후 연도 컬럼들의 자료형을 출력하세요.
yearDF.dtypes.head()

1970    int64
1971    int64
1972    int64
1973    int64
1974    int64
dtype: object

In [17]:
## 4. 전체 결측치 개수를 출력하세요.
#print(f"[년도별 결측치 개수]\n{yearDF.isna().sum()}")
print(f"[전  체 결측치 개수]  {yearDF.isna().sum().sum()}개")

[전  체 결측치 개수]  0개