### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [2]:
## 모듈 로딩
import pandas as pd

In [3]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [4]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [5]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [6]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [7]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [8]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [9]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [10]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [11]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    324 non-null    object
 1   전입지별    324 non-null    object
 2   1970    324 non-null    int64
 3   1971    324 non-null    int64
 4   1972    324 non-null    int64
 5   1973    324 non-null    int64
 6   1974    324 non-null    int64
 7   1975    324 non-null    int64
 8   1976    324 non-null    int64
 9   1977    324 non-null    int64
 10  1978    324 non-null    int64
 11  1979    324 non-null    int64
 12  1980    324 non-null    int64
 13  1981    324 non-null    int64
 14  1982    324 non-null    int64
 15  1983    324 non-null    int64
 16  1984    324 non-null    int64
 17  1985    324 non-null    int64
 18  1986    324 non-null    int64
 19  1987    324 non-null    int64
 20  1988    324 non-null    int64
 21  1989    324 non-null    int64
 22  1990    324 non-null    int64
 23  1991    324 non-null    int64
 24  1992    324 non-null    int64
 25  1993    324 non-null    int64
 26  1994    324 non-null    int64
 27  1995    324 non-null    int64
 28  1996    324 non-null    int64
 29  1997    324 non-null    int64
 30  1998    324 non-null    int64
 31  1999    324 non-null    int64
 32  2000    324 non-null    int64
 33  2001    324 non-null    int64
 34  2002    324 non-null    int64
 35  2003    324 non-null    int64
 36  2004    324 non-null    int64
 37  2005    324 non-null    int64
 38  2006    324 non-null    int64
 39  2007    324 non-null    int64
 40  2008    324 non-null    int64
 41  2009    324 non-null    int64
 42  2010    324 non-null    int64
 43  2011    324 non-null    int64
 44  2012    324 non-null    int64
 45  2013    324 non-null    int64
 46  2014    324 non-null    int64
 47  2015    324 non-null    int64
 48  2016    324 non-null    int64
 49  2017    324 non-null    int64
dtypes: int64(48), object(2)
memory usage: 126.7+ KB

---
#### 문제 5) 서울특별시에서 다른 지역으로 전출한 데이터만 추출하세요.
* 서울특별시 ---> 다른 지역 이동
* 전출지별 : 서울특별시
* 전입지별 : 서울특별시가 아닌 지역명
---

In [12]:
## 전출지별 : 서울특벌시 ==> 전입지별 : 다른 지역 
## 전출지별의 NAN값 채우기
seoulDF = df.copy()
seoulDF["전출지별"] = seoulDF["전출지별"].ffill()
seoulDF.tail(10)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
315,제주특별자치도,세종특별자치시,0,0,0,0,0,0,0,0,...,0,0,0,0,58,74,134,188,210,255
316,제주특별자치도,경기도,727,817,420,641,702,1811,1351,1516,...,5223,5046,5022,4990,4655,4775,5291,5845,6520,6931
317,제주특별자치도,강원도,435,191,150,184,194,728,295,306,...,570,582,542,516,520,511,543,607,694,693
318,제주특별자치도,충청북도,42,59,116,82,115,185,205,128,...,519,475,478,518,484,433,546,621,726,754
319,제주특별자치도,충청남도,294,155,238,235,285,554,493,535,...,731,756,774,776,696,676,757,896,834,967
320,제주특별자치도,전라북도,139,202,141,210,219,415,392,408,...,668,579,672,561,551,516,609,683,733,768
321,제주특별자치도,전라남도,631,965,857,952,1133,2808,2608,2652,...,1143,1123,1002,1026,966,1001,928,1062,1127,1102
322,제주특별자치도,경상북도,374,619,468,576,625,1123,1141,1004,...,761,704,738,756,699,781,728,903,931,994
323,제주특별자치도,경상남도,474,479,440,571,1208,1517,863,1122,...,1517,1474,1324,1367,1227,1278,1223,1500,1448,1501
324,제주특별자치도,제주특별자치도,9290,12427,12210,16158,19580,34221,23291,31028,...,59564,55673,55507,59846,54280,60607,59673,59036,66444,63275

In [13]:
## 전출지별 : 서울특벌시 ==> 전입지별 : 다른 지역 
## 전출지별의 NAN값 채우기
#seoulDF[ seoulDF["전출지별"]=="서울특별시" ].head(2)
boolSR = seoulDF["전출지별"]=="서울특별시" 
seoulDF = seoulDF[boolSR]
seoulDF.shape, seoulDF.columns

((18, 50),
 Index(['전출지별', '전입지별', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
        '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985',
        '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994',
        '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
        '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
        '2013', '2014', '2015', '2016', '2017'],
       dtype='object'))

In [14]:
## 전출지별 컬럼 동일값으로 삭제
seoulDF = seoulDF.drop(columns='전출지별')
seoulDF.shape

(18, 49)

In [15]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF[ (seoulDF['전입지별'] != '전국') & (seoulDF['전입지별'] != '서울특별시') ]

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
21,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
22,대구광역시,0,0,0,0,0,0,0,0,0,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
23,인천광역시,0,0,0,0,0,0,0,0,0,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
24,광주광역시,0,0,0,0,0,0,0,0,0,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
25,대전광역시,0,0,0,0,0,0,0,0,0,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
26,울산광역시,0,0,0,0,0,0,0,0,0,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
27,세종특별자치시,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2998,2851,6481,7550,5943,5813
28,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
29,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
30,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
31,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
32,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
33,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
34,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
35,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
36,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [16]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF[~ seoulDF["전입지별"].isin(["서울특별시", "전국"]) ]

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
21,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
22,대구광역시,0,0,0,0,0,0,0,0,0,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
23,인천광역시,0,0,0,0,0,0,0,0,0,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
24,광주광역시,0,0,0,0,0,0,0,0,0,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
25,대전광역시,0,0,0,0,0,0,0,0,0,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
26,울산광역시,0,0,0,0,0,0,0,0,0,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
27,세종특별자치시,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2998,2851,6481,7550,5943,5813
28,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
29,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
30,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
31,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
32,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
33,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
34,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
35,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
36,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [17]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF.query('전입지별!="서울특별시" & 전입지별 !="전국"').reset_index(drop=True)

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
1,대구광역시,0,0,0,0,0,0,0,0,0,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
2,인천광역시,0,0,0,0,0,0,0,0,0,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
3,광주광역시,0,0,0,0,0,0,0,0,0,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
4,대전광역시,0,0,0,0,0,0,0,0,0,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
5,울산광역시,0,0,0,0,0,0,0,0,0,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
6,세종특별자치시,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2998,2851,6481,7550,5943,5813
7,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
8,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
9,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
10,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
11,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
12,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
13,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
14,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
15,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404