### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [22]:
## 모듈 로딩
import pandas as pd

In [23]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [24]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [25]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [26]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [27]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [28]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [29]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [30]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [31]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    324 non-null    object
 1   전입지별    324 non-null    object
 2   1970    324 non-null    int64
 3   1971    324 non-null    int64
 4   1972    324 non-null    int64
 5   1973    324 non-null    int64
 6   1974    324 non-null    int64
 7   1975    324 non-null    int64
 8   1976    324 non-null    int64
 9   1977    324 non-null    int64
 10  1978    324 non-null    int64
 11  1979    324 non-null    int64
 12  1980    324 non-null    int64
 13  1981    324 non-null    int64
 14  1982    324 non-null    int64
 15  1983    324 non-null    int64
 16  1984    324 non-null    int64
 17  1985    324 non-null    int64
 18  1986    324 non-null    int64
 19  1987    324 non-null    int64
 20  1988    324 non-null    int64
 21  1989    324 non-null    int64
 22  1990    324 non-null    int64
 23  1991    324 non-null    int64
 24  1992    324 non-null    int64
 25  1993    324 non-null    int64
 26  1994    324 non-null    int64
 27  1995    324 non-null    int64
 28  1996    324 non-null    int64
 29  1997    324 non-null    int64
 30  1998    324 non-null    int64
 31  1999    324 non-null    int64
 32  2000    324 non-null    int64
 33  2001    324 non-null    int64
 34  2002    324 non-null    int64
 35  2003    324 non-null    int64
 36  2004    324 non-null    int64
 37  2005    324 non-null    int64
 38  2006    324 non-null    int64
 39  2007    324 non-null    int64
 40  2008    324 non-null    int64
 41  2009    324 non-null    int64
 42  2010    324 non-null    int64
 43  2011    324 non-null    int64
 44  2012    324 non-null    int64
 45  2013    324 non-null    int64
 46  2014    324 non-null    int64
 47  2015    324 non-null    int64
 48  2016    324 non-null    int64
 49  2017    324 non-null    int64
dtypes: int64(48), object(2)
memory usage: 126.7+ KB

---
#### 문제 4) 특정 행과 열을 선택하세요.
[요구사항]
1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
2. 앞에서 10개 행만 출력하세요.
3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
---

In [37]:
## 1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
select_cols = ["전출지별", "전입지별", "1970", "1980", "1990", "2000", "2010", "2017"]
partDF = df[select_cols].reset_index(drop=True)
partDF.head(3)

  전출지별   전입지별     1970     1980     1990     2000     2010     2017
0   전국     전국  4046536  8258573  9459209  9009441  8226594  7154226
1   전국  서울특별시  1742813  2767816  2726492  2219407  1733015  1472937
2   전국  부산광역시   448577   904252   761684   595975   519334   439073

In [38]:
## 2. 앞에서 10개 행만 출력하세요.
print("[앞에서 10개 행]")
display(partDF.iloc[:10])

[앞에서 10개 행]

  전출지별     전입지별     1970     1980     1990     2000     2010     2017
0   전국       전국  4046536  8258573  9459209  9009441  8226594  7154226
1   전국    서울특별시  1742813  2767816  2726492  2219407  1733015  1472937
2   전국    부산광역시   448577   904252   761684   595975   519334   439073
3   전국    대구광역시        0        0   526547   477595   370817   321182
4   전국    인천광역시        0        0   567863   531318   462051   409465
5   전국    광주광역시        0        0   330810   301498   268574   208138
6   전국    대전광역시        0        0   296756   312560   262432   211449
7   전국    울산광역시        0        0        0   166690   161146   135199
8   전국  세종특별자치시        0        0        0        0        0    82073
9   전국      경기도   452060  1085764  1609933  2042327  2168820  1888324

In [39]:
## 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
print("[전출지별, 전입지별, 2017 컬럼]")
display(partDF.loc[:, ["전출지별", "전입지별", "2017"]].head())
display( partDF[["전출지별", "전입지별", "2017"]].head() )

[전출지별, 전입지별, 2017 컬럼]

  전출지별   전입지별     2017
0   전국     전국  7154226
1   전국  서울특별시  1472937
2   전국  부산광역시   439073
3   전국  대구광역시   321182
4   전국  인천광역시   409465

  전출지별   전입지별     2017
0   전국     전국  7154226
1   전국  서울특별시  1472937
2   전국  부산광역시   439073
3   전국  대구광역시   321182
4   전국  인천광역시   409465

In [40]:
## 4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
print(f"[0번 행의 2017년 이동자수] { partDF.loc[0, '2017']:,}명")

[0번 행의 2017년 이동자수] 7,154,226명