### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [3]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [4]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [5]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [6]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [7]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [8]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [9]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [10]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    324 non-null    object
 1   전입지별    324 non-null    object
 2   1970    324 non-null    int64
 3   1971    324 non-null    int64
 4   1972    324 non-null    int64
 5   1973    324 non-null    int64
 6   1974    324 non-null    int64
 7   1975    324 non-null    int64
 8   1976    324 non-null    int64
 9   1977    324 non-null    int64
 10  1978    324 non-null    int64
 11  1979    324 non-null    int64
 12  1980    324 non-null    int64
 13  1981    324 non-null    int64
 14  1982    324 non-null    int64
 15  1983    324 non-null    int64
 16  1984    324 non-null    int64
 17  1985    324 non-null    int64
 18  1986    324 non-null    int64
 19  1987    324 non-null    int64
 20  1988    324 non-null    int64
 21  1989    324 non-null    int64
 22  1990    324 non-null    int64
 23  1991    324 non-null    int64
 24  1992    324 non-null    int64
 25  1993    324 non-null    int64
 26  1994    324 non-null    int64
 27  1995    324 non-null    int64
 28  1996    324 non-null    int64
 29  1997    324 non-null    int64
 30  1998    324 non-null    int64
 31  1999    324 non-null    int64
 32  2000    324 non-null    int64
 33  2001    324 non-null    int64
 34  2002    324 non-null    int64
 35  2003    324 non-null    int64
 36  2004    324 non-null    int64
 37  2005    324 non-null    int64
 38  2006    324 non-null    int64
 39  2007    324 non-null    int64
 40  2008    324 non-null    int64
 41  2009    324 non-null    int64
 42  2010    324 non-null    int64
 43  2011    324 non-null    int64
 44  2012    324 non-null    int64
 45  2013    324 non-null    int64
 46  2014    324 non-null    int64
 47  2015    324 non-null    int64
 48  2016    324 non-null    int64
 49  2017    324 non-null    int64
dtypes: int64(48), object(2)
memory usage: 126.7+ KB

---
#### 문제 6) 서울특별시로 전입한 지역의 데이터 추출한 문제입니다

[요구사항]
1. 전출지별이  "부산광역시", "대구광역시", "인천광역시", "경기도"  중 하나인 행만 추출하세요.
2. 전입지별, 1990, 2000, 2010, 2017 컬럼만 출력하세요.
3. 2017년 이동자수 기준으로 내림차순 정렬하세요.
---

[ SettingWithCopyWarning 경고 ]

- C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_33412\2741080109.py:5: SettingWithCopyWarning: 
- A value is trying to be set on a copy of a slice from a DataFrame
- See the caveats in the documentation: 
- https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

* View란
    * 메모리 낭비를 줄이기 위해 원본 데이터를 복사하지 않고 일부를 바라보는 방식
    * 하지만 View를 수정하면 원본도 영향을 받을 수 있음

* [원인]
    * 원본 DataFrame에서 일부 행/열을 추출해서 만든 DataFrame에 값을 수정/삭제하려고 할 때 발생
    * inplace=True로 원본에 적용할 경우 
    * 이 DataFrame이 원본의 일부인지 복사본인지 불명확
    * 수정한 내용이 원본에 반영될 수도 있고 안 될 수도 있음!!!
* [해결]
    - 일부 데이터를 추출한 뒤 별도로 작업할 목적이면 .copy()로 독립적인 DF로 작업

In [ ]:
# 1. 전출지별이  "부산광역시", "대구광역시", "인천광역시", "경기도"  중 하나인 행만 추출하세요.
## => 전입지별이 서울특별시 인 행 추출
mask = df['전입지별'] == '서울특별시'
inSeoulDF = df[mask]

inSeoulDF.drop(columns='전입지별', inplace=True)
inSeoulDF.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 2 to 308
Data columns (total 49 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   전출지별    18 non-null     object
 1   1970    18 non-null     int64
 2   1971    18 non-null     int64
 3   1972    18 non-null     int64
 4   1973    18 non-null     int64
 5   1974    18 non-null     int64
 6   1975    18 non-null     int64
 7   1976    18 non-null     int64
 8   1977    18 non-null     int64
 9   1978    18 non-null     int64
 10  1979    18 non-null     int64
 11  1980    18 non-null     int64
 12  1981    18 non-null     int64
 13  1982    18 non-null     int64
 14  1983    18 non-null     int64
 15  1984    18 non-null     int64
 16  1985    18 non-null     int64
 17  1986    18 non-null     int64
 18  1987    18 non-null     int64
 19  1988    18 non-null     int64
 20  1989    18 non-null     int64
 21  1990    18 non-null     int64
 22  1991    18 non-null     int64
 23  1992    18 non-null     int64
 24  1993    18 non-null     int64
 25  1994    18 non-null     int64
 26  1995    18 non-null     int64
 27  1996    18 non-null     int64
 28  1997    18 non-null     int64
 29  1998    18 non-null     int64
 30  1999    18 non-null     int64
 31  2000    18 non-null     int64
 32  2001    18 non-null     int64
 33  2002    18 non-null     int64
 34  2003    18 non-null     int64
 35  2004    18 non-null     int64
 36  2005    18 non-null     int64
 37  2006    18 non-null     int64
 38  2007    18 non-null     int64
 39  2008    18 non-null     int64
 40  2009    18 non-null     int64
 41  2010    18 non-null     int64
 42  2011    18 non-null     int64
 43  2012    18 non-null     int64
 44  2013    18 non-null     int64
 45  2014    18 non-null     int64
 46  2015    18 non-null     int64
 47  2016    18 non-null     int64
 48  2017    18 non-null     int64
dtypes: int64(48), object(1)
memory usage: 7.0+ KB

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_37348\2845538579.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inSeoulDF.drop(columns='전입지별', inplace=True)

In [12]:
## 전출지가 "부산광역시", "대구광역시", "인천광역시", "경기도"
mask = inSeoulDF["전출지별"].isin(["부산광역시", "대구광역시", "인천광역시", "경기도"])
inSeoulDF = inSeoulDF[mask]
inSeoulDF

,전출지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
38,부산광역시,24263,30144,18260,24251,30284,59914,43416,42685,48142,...,25249,24459,23116,23016,21437,19621,20616,19441,19236,19460
56,대구광역시,0,0,0,0,0,0,0,0,0,...,14824,15469,13915,13310,13838,13673,13735,13038,12802,13011
74,인천광역시,0,0,0,0,0,0,0,0,0,...,40479,38858,35670,33008,32216,33017,34380,33570,32486,32528
164,경기도,95388,95423,90470,107177,107518,207641,144524,154021,164771,...,323515,317952,285963,272407,254175,246464,249701,239557,234357,234448

In [13]:
# 2. 전입지별, 1990, 2000, 2010, 2017 컬럼만 출력하세요.
inSeoulDF = inSeoulDF[[ "전출지별", "1990", "2000", "2010", "2017"]]
inSeoulDF

      전출지별    1990    2000    2010    2017
38   부산광역시   34978   28564   23116   19460
56   대구광역시   19521   16970   13915   13011
74   인천광역시   43247   45970   35670   32528
164    경기도  282914  312616  285963  234448

In [14]:
# 3. 2017년 이동자수 기준으로 내림차순 정렬하세요.
inSeoulDF.sort_values(by="2000", ascending=False)

      전출지별    1990    2000    2010    2017
164    경기도  282914  312616  285963  234448
74   인천광역시   43247   45970   35670   32528
38   부산광역시   34978   28564   23116   19460
56   대구광역시   19521   16970   13915   13011