### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [49]:
## 모듈 로딩
import pandas as pd

In [50]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [51]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [52]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [53]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [54]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [55]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [56]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [57]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [58]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.dtypes

전출지별    object
전입지별    object
1970     int64
1971     int64
1972     int64
1973     int64
1974     int64
1975     int64
1976     int64
1977     int64
1978     int64
1979     int64
1980     int64
1981     int64
1982     int64
1983     int64
1984     int64
1985     int64
1986     int64
1987     int64
1988     int64
1989     int64
1990     int64
1991     int64
1992     int64
1993     int64
1994     int64
1995     int64
1996     int64
1997     int64
1998     int64
1999     int64
2000     int64
2001     int64
2002     int64
2003     int64
2004     int64
2005     int64
2006     int64
2007     int64
2008     int64
2009     int64
2010     int64
2011     int64
2012     int64
2013     int64
2014     int64
2015     int64
2016     int64
2017     int64
dtype: object

---
#### 문제 7) query()를 사용하여 2017년 이동자수가 100000명 이상인 데이터를 추출하세요.

[요구사항]
1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
4. 2017년 이동자수 기준으로 내림차순 정렬하세요.

[주의사항]
- 컬럼명이 숫자 형태이면 query()에서 사용하기 어려울 수 있습니다.
- 필요한 경우 2017 컬럼명을 "Y2017"과 같이 변경한 후 query()를 사용하세요.
---

In [59]:
## 1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
partDF = df.copy()
#partDF[partDF.columns[2:]] = partDF[partDF.columns[2:]].replace("-", 0).astype("int")

In [60]:
#partDF[partDF.columns[2:]] = partDF[partDF.columns[2:]].mask(partDF[partDF.columns[2:]] == "-", 0).astype(int)

In [61]:
#partDF = partDF[partDF.columns[2:]]

In [62]:
partDF.dtypes.head(3)

전출지별    object
전입지별    object
1970     int64
dtype: object

In [63]:
## 2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
## 2-1: 불린인덱싱
partDF[ partDF['2017'] >= 1000000 ].sort_index(axis=1, ascending=False)

,전출지별,전입지별,2017,2016,2015,2014,2013,2012,2011,2010,...,1979,1978,1977,1976,1975,1974,1973,1972,1971,1970
1,전국,전국,7154226,7378430,7755286,7629098,7411784,7506691,8127195,8226594,...,7324380,8410276,7397623,6773250,9011440,5297969,4860418,3687938,4210164,4046536
2,전국,서울특별시,1472937,1515602,1589431,1573594,1520090,1555281,1721748,1733015,...,2589667,3307439,2893403,2756510,3396662,2050392,1831858,1349333,1671705,1742813
10,전국,경기도,1888324,1958593,1993080,1891775,1895434,1944962,2062422,2168820,...,984187,985879,880019,770036,1006818,579194,542224,418045,533375,452060
19,서울특별시,전국,1571423,1655859,1726687,1661425,1620640,1658928,1834806,1848038,...,2441242,3028911,2678007,2495620,2937093,1819660,1647268,1210559,1419016,1448985
20,서울특별시,서울특별시,1018807,1061915,1129529,1098023,1053008,1069300,1215122,1199708,...,1883742,2518286,2212213,2041724,2401970,1511726,1345508,985945,1158556,1232619
163,경기도,전국,1772162,1824976,1898312,1834379,1821303,1862209,1986623,2026383,...,786271,817561,753564,645942,825258,484597,454426,382945,412098,353535
172,경기도,경기도,1259187,1301101,1346264,1275072,1274495,1294565,1387806,1435269,...,496327,529175,492040,395632,493101,309489,284129,235877,263045,212365

In [64]:
## 2-2. query()메서드
## -> query()에서 숫자 컬럼명을 바로 쓰기 어렵기 때문에 2017 컬럼명을 변경
#partDF.query("2017 >= 100000")
partDF = partDF.rename(columns={'2017': "Y2017"})

# partDF = partDF.rename( columns={str(year): "Y" + str(year) for year in range(1970, 2018)} )
# print(partDF.shape, partDF.columns, sep='\n')

partDF = partDF.query("Y2017 >= 100000")
partDF

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,Y2017
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,전국,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,전국,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,전국,대구광역시,0,0,0,0,0,0,0,0,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182
5,전국,인천광역시,0,0,0,0,0,0,0,0,...,565585,478169,462051,499567,468666,461613,452297,473223,441646,409465
6,전국,광주광역시,0,0,0,0,0,0,0,0,...,268757,293879,268574,260561,228612,226696,243066,224603,213176,208138
7,전국,대전광역시,0,0,0,0,0,0,0,0,...,263532,252424,262432,264244,239635,230858,239559,220774,219252,211449
8,전국,울산광역시,0,0,0,0,0,0,0,0,...,181662,159953,161146,164963,161433,159492,176015,170393,148190,135199
10,전국,경기도,452060,533375,418045,542224,579194,1006818,770036,880019,...,2195585,2175681,2168820,2062422,1944962,1895434,1891775,1993080,1958593,1888324
11,전국,강원도,160959,183964,161637,241663,184385,326365,239946,246070,...,252193,249191,241738,236077,225896,217917,228369,227125,223484,211653
12,전국,충청북도,100041,111901,99573,122988,125958,246251,164008,163716,...,244672,232872,235671,228594,212263,215973,215944,214626,202679,197177
13,전국,충청남도,192979,205632,190175,239750,217167,482034,292314,341491,...,355294,329626,317853,321187,287195,281428,289627,289952,286764,288738
14,전국,전라북도,136856,165843,153347,185754,173873,368163,236947,271557,...,322495,314137,305789,308011,271835,258198,274337,261832,248188,232047
15,전국,전라남도,177536,243793,218180,301023,313318,572277,426056,460561,...,277906,281051,265600,261239,239026,244329,260278,250104,234132,227504
16,전국,경상북도,407643,470732,519508,605014,585406,1241147,739579,855263,...,363297,367244,354575,363511,335362,329118,337041,344730,315652,311061
17,전국,경상남도,212521,214358,196534,282238,358116,514805,386917,457139,...,487356,485349,481955,473757,414556,427658,462239,455384,411952,413179
18,전국,제주특별자치도,14551,19064,19404,25845,29176,50939,36273,43287,...,80124,76575,77224,82708,79501,88851,92508,97580,106825,105027
19,서울특별시,전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,...,2083352,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423
20,서울특별시,서울특별시,1232619,1158556,985945,1345508,1511726,2401970,2041724,2212213,...,1426213,1286855,1199708,1215122,1069300,1053008,1098023,1129529,1061915,1018807
28,서울특별시,경기도,130149,150313,93333,143234,149045,253705,202276,207722,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
37,부산광역시,전국,376059,328367,319360,414661,554013,694445,629165,696120,...,549106,549094,547800,532906,481652,496161,500802,520591,480407,467471
39,부산광역시,부산광역시,307900,248102,245789,316491,447094,490794,462171,511015,...,387878,391404,393530,376930,340468,358352,353282,376345,340521,321606
55,대구광역시,전국,0,0,0,0,0,0,0,0,...,422676,411288,382657,383310,359206,363224,365739,364364,337488,333118
58,대구광역시,대구광역시,0,0,0,0,0,0,0,0,...,311113,298755,274649,276495,254661,258107,252642,259185,240722,236143
73,인천광역시,전국,0,0,0,0,0,0,0,0,...,556166,476071,458439,470758,440872,439578,442973,463685,435869,411135
77,인천광역시,인천광역시,0,0,0,0,0,0,0,0,...,389945,318898,303966,325441,297979,297446,295375,314622,290783,266394
91,광주광역시,전국,0,0,0,0,0,0,0,0,...,268310,290771,265043,259282,230437,229288,246043,233875,221074,216256
96,광주광역시,광주광역시,0,0,0,0,0,0,0,0,...,182473,206147,183496,179871,152570,155265,164321,150777,145582,142174
109,대전광역시,전국,0,0,0,0,0,0,0,0,...,269142,258182,263477,260900,239136,230547,248397,241390,229883,227624
115,대전광역시,대전광역시,0,0,0,0,0,0,0,0,...,174748,166836,175962,175460,152381,148793,156961,139609,138876,131656
127,울산광역시,전국,0,0,0,0,0,0,0,0,...,177756,164984,164671,163091,157427,157185,173229,170473,155812,147116
163,경기도,전국,353535,412098,382945,454426,484597,825258,645942,753564,...,2094988,2081528,2026383,1986623,1862209,1821303,1834379,1898312,1824976,1772162
164,경기도,서울특별시,95388,95423,90470,107177,107518,207641,144524,154021,...,323515,317952,285963,272407,254175,246464,249701,239557,234357,234448
172,경기도,경기도,212365,263045,235877,284129,309489,493101,395632,492040,...,1454951,1455865,1435269,1387806,1294565,1274495,1275072,1346264,1301101,1259187
181,강원도,전국,197181,218958,192371,277465,233685,386575,281828,291783,...,250883,247373,241183,231424,225184,214931,226284,222352,221592,209618
191,강원도,강원도,113485,128222,112559,180716,130356,212434,154239,162520,...,161854,158826,153165,147142,140649,136041,145250,140018,140921,130963
199,충청북도,전국,147916,156593,124530,156909,166708,324499,213011,220085,...,237759,230351,229707,220515,207622,212860,213577,213188,197668,194915
210,충청북도,충청북도,65127,71722,60135,79667,81662,156257,97992,101842,...,159835,151216,153067,145679,133461,139959,136614,133264,124156,119825
217,충청남도,전국,240241,255973,212546,277908,268495,562558,344295,384884,...,339765,317511,301675,302546,277346,268053,279817,279680,271446,269337
229,충청남도,충청남도,121675,138377,125416,165914,144920,315561,175247,218193,...,204302,187758,177372,179652,161743,159556,165101,163496,163006,161612
235,전라북도,전국,228126,240338,190364,238830,245518,505510,323710,353025,...,333045,318943,308237,306290,275126,260395,276900,264662,252607,239253
248,전라북도,전라북도,104671,126915,112660,137823,132220,271325,164485,197471,...,242371,234785,228881,228836,199254,189665,203725,193076,181657,167338
253,전라남도,전국,263908,329442,259182,360474,397292,705568,497144,537331,...,291224,288476,275661,266461,244080,246635,260874,246168,237337,230551
267,전라남도,전라남도,137252,200362,172986,245116,261202,445600,308898,349360,...,172644,172919,163343,159553,143423,151466,161491,147703,140958,137172
271,경상북도,전국,470142,528111,533098,630214,612614,1324401,798110,916540,...,377397,375551,358127,358695,340222,330983,338029,345307,318803,316642
286,경상북도,경상북도,326668,384273,427599,484785,442652,1003878,565093,683083,...,229333,228016,217642,223534,204248,201206,201259,209109,193354,193235
289,경상남도,전국,299797,298292,244230,341498,413442,631217,482042,509366,...,474327,474110,478709,469223,417328,423864,456164,450279,410180,409200
305,경상남도,경상남도,149016,146090,128191,179266,228442,318345,231525,275293,...,331312,332012,335387,326746,281109,293031,319925,311708,277204,275875

In [65]:
## 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
partDF = partDF[['전출지별','전입지별', 'Y2017']]
partDF.head()

  전출지별   전입지별    Y2017
1   전국     전국  7154226
2   전국  서울특별시  1472937
3   전국  부산광역시   439073
4   전국  대구광역시   321182
5   전국  인천광역시   409465

In [67]:
## 4. 2017년 이동자수 기준으로 내림차순 정렬하세요.
partDF = partDF.sort_values(by="Y2017", ascending=False).reset_index(drop=True)
partDF.head(3)

  전출지별 전입지별    Y2017
0   전국   전국  7154226
1   전국  경기도  1888324
2  경기도   전국  1772162